const symbolGroups = [
['XPINUSDT_PERP.A, UBUSDT_PERP.A, ZKCUSDT_PERP.A, TOSHIUSDT_PERP.A, STBLUSDT_PERP.A, 0GUSDT_PERP.A, BARDUSDT_PERP.A, ASTERUSDT_PERP.A, TRADOORUSDT_PERP.A, BLESSUSDT_PERP.A, FLUIDUSDT_PERP.A, COAIUSDT_PERP.A, HANAUSDT_PERP.A, MIRAUSDT_PERP.A, AKEUSDT_PERP.A, ORDERUSDT_PERP.A, XANUSDT_PERP.A, FFUSDT_PERP.A, EDENUSDT_PERP.A, NOMUSDT_PERP.A'],
['TRUTHUSDT_PERP.A, 2ZUSDT_PERP.A, EVAAUSDT_PERP.A, LYNUSDT_PERP.A, KGENUSDT_PERP.A, 4USDT_PERP.A, GIGGLEUSDT_PERP.A, MONUSDT_PERP.A, YBUSDT_PERP.A, METUSDT_PERP.A, EULUSDT_PERP.A, ENSOUSDT_PERP.A, CLOUSDT_PERP.A, RECALLUSDT_PERP.A, ZBTUSDT_PERP.A, LABUSDT_PERP.A, RIVERUSDT_PERP.A, BLUAIUSDT_PERP.A, TURTLEUSDT_PERP.A, APRUSDT_PERP.A'],
['ONUSDT_PERP.A, KITEUSDT_PERP.A, ATUSDT_PERP.A, CCUSDT_PERP.A, MMTUSDT_PERP.A, TRUSTUSDT_PERP.A, UAIUSDT_PERP.A, FOLKSUSDT_PERP.A, STABLEUSDT_PERP.A, JCTUSDT_PERP.A, ALLOUSDT_PERP.A, CLANKERUSDT_PERP.A, BEATUSDT_PERP.A, PIEVERSEUSDT_PERP.A, SENTUSDT_PERP.A, IRYSUSDT_PERP.A, POWERUSDT_PERP.A, WETUSDT_PERP.A, NIGHTUSDT_PERP.A, USUSDT_PERP.A'],
['CYSUSDT_PERP.A, RAVEUSDT_PERP.A, ZKPUSDT_PERP.A, GUAUSDT_PERP.A, LITUSDT_PERP.A, BREVUSDT_PERP.A, COLLECTUSDT_PERP.A, MAGMAUSDT_PERP.A, ZAMAUSDT_PERP.A, FOGOUSDT_PERP.A, FRAXUSDT_PERP.A, SPORTFUNUSDT_PERP.A, AIAUSDT_PERP.A, ACUUSDT_PERP.A, ELSAUSDT_PERP.A, SKRUSDT_PERP.A, SPACEUSDT_PERP.A, FIGHTUSDT_PERP.A, BIRBUSDT_PERP.A, GWEIUSDT_PERP.A'],
['MEGAUSDT_PERP.A, INXUSDT_PERP.A, TRIAUSDT_PERP.A, ESPUSDT_PERP.A, AZTECUSDT_PERP.A, OPNUSDT_PERP.A, ROBOUSDT_PERP.A, KATUSDT_PERP.A, MANTRAUSDT_PERP.A, CFGUSDT_PERP.A, EDGEUSDT_PERP.A, BSBUSDT_PERP.A, BASEDUSDT_PERP.A, PRLUSDT_PERP.A, GENIUSUSDT_PERP.A, CHIPUSDT_PERP.A, OPGUSDT_PERP.A, AIGENSYNUSDT_PERP.A, BILLUSDT_PERP.A, PHAROSUSDT_PERP.A'],

];





module.exports = symbolGroups;

