const symbolGroups = [
['FFUSDT_PERP.A, EDENUSDT_PERP.A, NOMUSDT_PERP.A, TRUTHUSDT_PERP.A, 2ZUSDT_PERP.A, EVAAUSDT_PERP.A, LYNUSDT_PERP.A, KGENUSDT_PERP.A, 4USDT_PERP.A, GIGGLEUSDT_PERP.A, MONUSDT_PERP.A, YBUSDT_PERP.A, METUSDT_PERP.A, EULUSDT_PERP.A, ENSOUSDT_PERP.A, CLOUSDT_PERP.A, RECALLUSDT_PERP.A, ZBTUSDT_PERP.A, LABUSDT_PERP.A, RIVERUSDT_PERP.A'],
['币安人生USDT_PERP.A, BLUAIUSDT_PERP.A, TURTLEUSDT_PERP.A, APRUSDT_PERP.A, ONUSDT_PERP.A, KITEUSDT_PERP.A, ATUSDT_PERP.A, CCUSDT_PERP.A, MMTUSDT_PERP.A, TRUSTUSDT_PERP.A, UAIUSDT_PERP.A, FOLKSUSDT_PERP.A, STABLEUSDT_PERP.A, JCTUSDT_PERP.A, ALLOUSDT_PERP.A, CLANKERUSDT_PERP.A, BEATUSDT_PERP.A, PIEVERSEUSDT_PERP.A, SENTUSDT_PERP.A, IRYSUSDT_PERP.A'],
['POWERUSDT_PERP.A, WETUSDT_PERP.A, NIGHTUSDT_PERP.A, USUSDT_PERP.A, CYSUSDT_PERP.A, RAVEUSDT_PERP.A, ZKPUSDT_PERP.A, GUAUSDT_PERP.A, LITUSDT_PERP.A, BREVUSDT_PERP.A, COLLECTUSDT_PERP.A, MAGMAUSDT_PERP.A, ZAMAUSDT_PERP.A, FOGOUSDT_PERP.A, FRAXUSDT_PERP.A, SPORTFUNUSDT_PERP.A, AIAUSDT_PERP.A, ACUUSDT_PERP.A, 我踏马来了USDT_PERP.A, ELSAUSDT_PERP.A'],
['SKRUSDT_PERP.A, SPACEUSDT_PERP.A, FIGHTUSDT_PERP.A, BIRBUSDT_PERP.A, GWEIUSDT_PERP.A, MEGAUSDT_PERP.A, INXUSDT_PERP.A, TRIAUSDT_PERP.A, ESPUSDT_PERP.A, AZTECUSDT_PERP.A, OPNUSDT_PERP.A, ROBOUSDT_PERP.A, KATUSDT_PERP.A, MANTRAUSDT_PERP.A, 龙虾USDT_PERP.A, CFGUSDT_PERP.A, EDGEUSDT_PERP.A, BSBUSDT_PERP.A, XAUTUSDT_PERP.A, BASEDUSDT_PERP.A'],
['PRLUSDT_PERP.A, GENIUSUSDT_PERP.A, CHIPUSDT_PERP.A, OPGUSDT_PERP.A, AIGENSYNUSDT_PERP.A, BILLUSDT_PERP.A, PHAROSUSDT_PERP.A, STARUSDT_PERP.A, CTRUSDT_PERP.A, SLXUSDT_PERP.A, ZESTUSDT_PERP.A, BTWUSDT_PERP.A, REUSDT_PERP.A, ARXUSDT_PERP.A, OUSDT_PERP.A, CAPUSDT_PERP.A, GRAMUSDT_PERP.A, DATAIPUSDT_PERP.A, GRVTUSDT_PERP.A, DOSUSDT_PERP.A'],

];





module.exports = symbolGroups;

