const symbolGroups = [
['PORT3USDT_PERP.A,1000000BOBUSDT_PERP.A,LAUSDT_PERP.A,BUSDT_PERP.A,SOONUSDT_PERP.A,HUMAUSDT_PERP.A,ZKJUSDT_PERP.A,CVCUSDT_PERP.A,AGTUSDT_PERP.A,AWEUSDT_PERP.A,ASRUSDT_PERP.A,ALPINEUSDT_PERP.A,B2USDT_PERP.A,MILKUSDT_PERP.A,SYRUPUSDT_PERP.A,SXTUSDT_PERP.A,SLPUSDT_PERP.A,ZORAUSDT_PERP.A,TAGUSDT_PERP.A,ZRCUSDT_PERP.A'],
['ESPORTSUSDT_PERP.A,PUMPUSDT_PERP.A,CROSSUSDT_PERP.A,AINUSDT_PERP.A,CUSDT_PERP.A,VELVETUSDT_PERP.A,OGUSDT_PERP.A,TREEUSDT_PERP.A,A2ZUSDT_PERP.A,LINEAUSDT_PERP.A,WLFIUSDT_PERP.A,SOMIUSDT_PERP.A,ARIAUSDT_PERP.A,TAKEUSDT_PERP.A,AVNTUSDT_PERP.A,WLFIUSDC_PERP.A,MITOUSDT_PERP.A,BASUSDT_PERP.A,HEMIUSDT_PERP.A,PTBUSDT_PERP.A'],
['QUSDT_PERP.A,SAPIENUSDT_PERP.A,CUDISUSDT_PERP.A,XPLUSDT_PERP.A,BTRUSDT_PERP.A,USELESSUSDT_PERP.A,AIOUSDT_PERP.A,XNYUSDT_PERP.A,CARVUSDT_PERP.A,YALAUSDT_PERP.A,TOWNSUSDT_PERP.A,PROVEUSDT_PERP.A,INUSDT_PERP.A,COAIUSDT_PERP.A,HANAUSDT_PERP.A,FLUIDUSDT_PERP.A,LIGHTUSDT_PERP.A,0GUSDT_PERP.A,BARDUSDT_PERP.A,ASTERUSDT_PERP.A'],
['TRADOORUSDT_PERP.A,BLESSUSDT_PERP.A,XANUSDT_PERP.A,XPINUSDT_PERP.A,ZKCUSDT_PERP.A,AIAUSDT_PERP.A,TOSHIUSDT_PERP.A,STBLUSDT_PERP.A,OPENUSDT_PERP.A,FLOCKUSDT_PERP.A,SKYUSDT_PERP.A,UBUSDT_PERP.A,HOLOUSDT_PERP.A,BREVUSDT_PERP.A,XAGUSDT_PERP.A,ZAMAUSDT_PERP.A,FOGOUSDT_PERP.A,ZKPUSDT_PERP.A,GUAUSDT_PERP.A,IRUSDT_PERP.A'],
['LITUSDT_PERP.A,COLLECTUSDT_PERP.A,MAGMAUSDT_PERP.A,RLSUSDT_PERP.A,POWERUSDT_PERP.A,WETUSDT_PERP.A,NIGHTUSDT_PERP.A,USUSDT_PERP.A,RAVEUSDT_PERP.A,SENTUSDT_PERP.A,GAIBUSDT_PERP.A,BOBUSDT_PERP.A,MONUSDT_PERP.A,CCUSDT_PERP.A,ALLOUSDT_PERP.A,PLANCKUSDT_PERP.A,CLANKERUSDT_PERP.A,BEATUSDT_PERP.A,PIEVERSEUSDT_PERP.A,KITEUSDT_PERP.A'],

];





module.exports = symbolGroups;

